# Generated by Django 4.1.7 on 2023-02-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('Non It', 'Non It'), ('Mobile Phones', 'Mobile Phones')], max_length=100),
        ),
    ]
